# Generated by Django 6.0.1 on 2026-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CcVehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_num', models.CharField(max_length=20)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('tank_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cc_vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCustomer',
            fields=[
                ('cc_id', models.AutoField(primary_key=True, serialize=False)),
                ('cc_name', models.CharField(max_length=200)),
                ('cc_address', models.TextField(blank=True, null=True)),
                ('cc_city', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_state', models.CharField(blank=True, max_length=50, null=True)),
                ('cc_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('cc_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('cc_email', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('trxn_datetime', models.DateTimeField()),
                ('chit_num', models.IntegerField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DipStockChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dip_stock_chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fuel_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fuels',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_name', models.CharField(max_length=50)),
                ('shorthand', models.CharField(max_length=10)),
                ('hsn_code', models.IntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fuels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nozzles',
            fields=[
                ('nozzleid', models.AutoField(primary_key=True, serialize=False)),
                ('nozzle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('du_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nozzles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oil_Company',
            fields=[
                ('oil_comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('oc_name', models.CharField(max_length=100)),
                ('oc_shorthand', models.CharField(max_length=10)),
                ('oc_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oil_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentsData',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pumps',
            fields=[
                ('pump_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact1', models.CharField(blank=True, max_length=15, null=True)),
                ('contact2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('petrol', models.BooleanField(blank=True, null=True)),
                ('petrol95', models.BooleanField(blank=True, null=True)),
                ('petrol100', models.BooleanField(blank=True, null=True)),
                ('diesel', models.BooleanField(blank=True, null=True)),
                ('diesel_turbo', models.BooleanField(blank=True, null=True)),
                ('cng', models.BooleanField(blank=True, null=True)),
                ('electric', models.BooleanField(blank=True, null=True)),
                ('lubes', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pumps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_date', models.DateField()),
                ('reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('testing', models.IntegerField(blank=True, null=True)),
                ('meter_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'readings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankStock',
            fields=[
                ('trxn_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_date', models.DateField()),
                ('dip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dip_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decant_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tank_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankTable',
            fields=[
                ('tank_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_dip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tank_table',
                'managed': False,
            },
        ),
    ]
